function filtermedian(img)
    I = imread(img);
    
    [tinggi,lebar] = size(I);
    %disp(tinggi);
    %disp(lebar);
    J = I;
    for baris = 2 : tinggi-1
        for kolom = 2 : lebar-1
            med = median([I(baris,kolom+1) ...
                I(baris-1,kolom+1) ...
                I(baris-1,kolom) ...
                I(baris-1,kolom-1) ...
                I(baris,kolom-1) ...
                I(baris+1,kolom-1) ...
                I(baris+1,kolom) ...
                I(baris+1,kolom+1) ...
                I(baris,kolom)]);
            J(baris,kolom) = med;         
        end
    end
    subplot(1,2,1); imshow(I); title('Original image');
    subplot(1,2,2); imshow(J); title('Modified image');
end