function filterbatas()
    I = imread('images/mobil.tif');
    
    [tinggi,lebar] = size(I);
    %disp(tinggi);
    %disp(lebar);
    J = I;
    for baris = 2 : tinggi-1
        for kolom = 2 : lebar-1
            minPx = min([I(baris,kolom+1) ...
                I(baris-1,kolom+1) ...
                I(baris-1,kolom) ...
                I(baris-1,kolom-1) ...
                I(baris,kolom-1) ...
                I(baris+1,kolom-1) ...
                I(baris+1,kolom) ...
                I(baris+1,kolom+1)]);
            maxPx = max([I(baris,kolom+1) ...
                I(baris-1,kolom+1) ...
                I(baris-1,kolom) ...
                I(baris-1,kolom-1) ...
                I(baris,kolom-1) ...
                I(baris+1,kolom-1) ...
                I(baris+1,kolom) ...
                I(baris+1,kolom+1)]);
            if J(baris,kolom) < minPx
                J(baris,kolom) = minPx;
            else 
                if J(baris,kolom) > maxPx
                    J(baris,kolom) = maxPx;
                end
            end
         
        end
    end
    imshow(I);
    figure, imshow(J);
end