function J = filterrerata(I)
    [tinggi,lebar] = size(I);
    %disp(tinggi);
    %disp(lebar);
    J = I;
    for baris = 2 : tinggi-1
        for kolom = 2 : lebar-1
            jum = sum([I(baris,kolom+1) ...
                I(baris-1,kolom+1) ...
                I(baris-1,kolom) ...
                I(baris-1,kolom-1) ...
                I(baris,kolom-1) ...
                I(baris+1,kolom-1) ...
                I(baris+1,kolom) ...
                I(baris+1,kolom+1) ...
                I(baris,kolom)]);
            J(baris,kolom) = uint8(jum/9);         
        end
    end
end