function J = filtermedian(I)
    
    [tinggi,lebar] = size(I);
    %disp(tinggi);
    %disp(lebar);
    J = I;
    for baris = 2 : tinggi-1
        for kolom = 2 : lebar-1
            med = median([I(baris,kolom+1) ...
                I(baris-1,kolom+1) ...
                I(baris-1,kolom) ...
                I(baris-1,kolom-1) ...
                I(baris,kolom-1) ...
                I(baris+1,kolom-1) ...
                I(baris+1,kolom) ...
                I(baris+1,kolom+1) ...
                I(baris,kolom)]);
            J(baris,kolom) = med;         
        end
    end
end